---

  # --------------------------------------------------- 
  # Fichier de paramètres : les comptes Oracle
  # --------------------------------------------------- 

  role_separation: false
  oracle_user: oracle
  grid_user: grid


  oracle_users:         # Passwd :Oracle123
   - { username: oracle, uid: 1001, primgroup: oinstall, othergroups: "dba,asmdba,backupdba,dgdba,kmdba,oper", passwd: "$6$0xHoAXXF$K75HKb64Hcb/CEcr3YEj2LGERi/U2moJgsCK.ztGxLsKoaXc4UBiNZPL0hlxB5ng6GL.gyipfQOOXplzcdgvD0" }

  grid_users:
   - { username: grid, uid: 1000, primgroup: oinstall, othergroups: "asmadmin,asmdba,asmoper,dba", passwd: "$6$0xHoAXXF$K75HKb64Hcb/CEcr3YEj2LGERi/U2moJgsCK.ztGxLsKoaXc4UBiNZPL0hlxB5ng6GL.gyipfQOOXplzcdgvD0" }


  oracle_user_home: "/home/{{ oracle_user }}"
  grid_user_home: "/home/{{ grid_user }}"
  oracle_group: oinstall
  oper_group: oper
  dba_group: dba
  asmoper_group: asmoper
  asmdba_group: asmdba
  asmadmin_group: asmadmin

  oracle_groups:
    - { group: asmdba, gid: 1004 }
    - { group: asmoper, gid: 1005 }
    - { group: asmadmin, gid: 1003 }
    - { group: oinstall, gid: 1000}
    - { group: dba, gid: 1001 }
    - { group: backupdba, gid: 1006 }
    - { group: oper, gid: 1002 }
    - { group: dgdba, gid: 1007 }
    - { group: kmdba, gid: 1008 }


  #----------------------------------------------------------------------
  # paramètres security limits pour une installation Oracle
  #----------------------------------------------------------------------
  oracle_seclimits:
      - "* soft nproc 2047"
      - "* hard nproc 16384"
      - "* soft nofile 1024"
      - "* hard nofile 65536"
      - "* soft memlock {{ ((0.9 * ansible_memtotal_mb)*1024*1024)|round|int }}"
      - "* hard memlock {{ ((0.9 * ansible_memtotal_mb)*1024*1024)|round|int }}"
      - "* soft stack 10240"
      - "* hard stack 32768"
      - "* soft core unlimited"
      - "* hard core unlimited"

  #----------------------------------------------------------------------
  # paramètres grub
  #----------------------------------------------------------------------
  disable_numa_boot: true