#--------------------------------------------------------------------
# paramètres commun
# dans cette section ne rien modifier sauf si besoin
#--------------------------------------------------------------------

role_separation: true
grid_install_user: "{% if role_separation==true %}{{ grid_user }}{% else %}{{ oracle_user }}{% endif %}"

# u01_free_space 4 Go pour l'install et 4 Go pour transfert et decompression des zip
u01_free_space_gb: 8
tmp_free_space_gb: 1
etc_free_spage_gb: 1
var_free_spage_gb: 1

#--------------------------------------------------------------------
# paramètres d'installation grid infra
#--------------------------------------------------------------------
gi_user: "grid"
gi_response_file: "install_gi_{{ gi_version }}.rsp"

#--------------------------------------------------------------------
# paramètres d'installation des binaires de la base
#--------------------------------------------------------------------
db_user: "oracle"

db_edition: "EE"
db_response_file: "install_db_{{ db_version }}_{{ db_edition }}.rsp"

